### ISSUE TITLE
Incorrect behavior using loadPackage

### ISSUE THREAD

**Issue by lucamata** [pzinn/Macaulay2Web#19]
When trying to upload a local package, using _loadPackage "..."_, M2Web returns some weird parser errors.
It doesn't seem to recognize basic _Macaulay2_ instructions or language delimiters.
To verify this malfunction, one can download a (error free) M2 package from official repository and upload it in M2Web: non-existent syntactic errors will be reported and the package will not be loaded.

```
loadPackage "Binomials"

stdio:48:1:(3): error: mutable unexported unset symbol(s) in package Binomials: 'Im', 'pc', 'LLL', 'radical', 'eliminate', 'bottomlattice'
Binomials.m2:904:11-904:13: here is the first use of 'Im'
Binomials.m2:905:11-905:13: here is the first use of 'pc'
Binomials.m2:184:13-184:16: here is the first use of 'LLL'
Binomials.m2:1180:41-1180:48: here is the first use of 'radical'
Binomials.m2:240:20-240:29: here is the first use of 'eliminate'
Binomials.m2:906:37-906:50: here is the first use of 'bottomlattice'
```

```
loadPackage "MonomialAlgebras"

-- storing configuration for package Topcom in /home/m2user/.Macaulay2/init-Topcom.m2
-- storing configuration for package MonomialAlgebras in /home/m2user/.Macaulay2/init-MonomialAlgebras.m2
MonomialAlgebras.m2:461:1:(2):[7]: error: missing semicolon or comma on previous line?
stdio:49:1:(3): --backtrace: parse error--
```

**Comment by pzinn** [comment]
thanks. there's definitely something fishy going on. Investigating.

**Comment by pzinn** [comment]
With the last server upgrade, I changed the way files are uploaded. Unfortunately it seems there's a bug with the package I'm using for the new file upload and files seem corrupted (which is really bad needless to say). I think this is the source of your problems. Will try to fix ASAP.

**Comment by pzinn** [comment]
Changed libraries, restarted server. Please try again and let me know how it goes.

**Comment by lucamata** [comment]
I have just tried and it seems to work fine. Thanks

**Comment by pzinn** [comment]
looks like switching to multer 777e6bb8d7c2f7db8463259171221533606a5e5d did the trick. and no chance of switching back to formidable, considering my issue https://github.com/node-formidable/formidable/issues/693 got closed w/o any attempt to fix it.
