### ISSUE TITLE
Is the M2 server down?

### ISSUE THREAD

**Issue by fragandi** [pzinn/Macaulay2Web#31]
Hi there, I just tried to restart M2 on the Macaulay2Web interface, and I got this error

Macaulay2, version 1.21
/usr/share/Macaulay2/Core/option.m2:13:0:(1): error: missing semicolon or comma on previous line?
../pzinn/M2/M2/Macaulay2/m2/startup.m2.in:66:23:(0): error: --backtrace: parse error--

I am pretty sure this might be an error of the interface, but reporting in just in case.

**Comment by pzinn** [comment]
thanks for reporting! my guess is this is what happened:
recently, I changed a setting so users can change the code of Macaulay2 itself. I had not realized a side effect would be that users could potentially break Macaulay2 by introducing bugs in there. This has become particularly easy now that error messages contain links to the source code. I might revert this change next update, I need to think about it.
In the meantime can you please do the following:
go to the CHAT window and type `/kill` -- this should reboot your Macaulay2 container. After that press Reset and see if things are back to normal. Let me know!

**Comment by fragandi** [comment]
This worked!
